config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: {
    # confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'user/passwords',
    registrations: 'user/registrations',
    sessions: 'user/sessions',
    # unlocks: 'users/unlocks',
  }
  # devise_for :users

  resources :challenges do
    resources :submissions do
      member do
        post :like
      end
    end
  end

  resources :users

  get '/submissions', to: "submissions#index"
  root to: "challenges#index"
end

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Mosaic Web Dev</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to fa_icon('puzzle-piece', text: "Challenges"), challenges_path %></li>
        <li><%= link_to fa_icon(:users, text: "Leaderboard"), users_path %></li>
        <% if admin? %>
          <li>
            <%= link_to fa_icon('trophy', text: "Submissions"), submissions_path %>
          </li>
        <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><%= fa_icon :bell %></a></li>
        <% if user_signed_in? %>
          <%= render 'navbar/user_info' %>
        <% else %>
          <%= render 'navbar/signin' %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/navbar/_signin.html.erb
<li>
  <%= link_to "Sign in", new_user_session_path %>
</li>
<li>
  <%= link_to "Sign up", new_user_registration_path %>
</li>

<!-- <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login<span class="caret"></span></a>
  <div class="dropdown-menu" style="padding:17px;">
    <form class="form" id="formLogin">
      <input name="username" id="username" type="text" placeholder="Username">
      <input name="password" id="password" type="password" placeholder="Password"><br>
      <button type="button" id="btnLogin" class="btn">Login</button>
    </form>
  </div>
</li>
 -->

app/views/navbar/_user_info.html.erb
<li>
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <%= current_user.display_name %>
    <span class="label label-info"><%= fa_icon 'star', text: current_user.cached_points %></span>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><a href="#">settings</a></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Sign out", destroy_user_session_path, method: :DELETE %></li>
  </ul>
</li>