config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: {
    # confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'user/passwords',
    registrations: 'user/registrations',
    sessions: 'user/sessions',
    # unlocks: 'users/unlocks',
  }
  # devise_for :users

  resources :challenges do
    resources :submissions do
      member do
        post :like
      end
    end
  end

  resources :users

  get '/submissions', to: "submissions#index"
  root to: "challenges#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, counter_cache: true
  before_create :refresh_cached_user_params
  after_commit :send_notification

  private

  def refresh_cached_user_params
    self.cached_user_name = user.display_name
    self.cached_user_email = user.email
  end

  def send_notification
    # title = "New Comment"
    # path = nil

    if commentable_type == "Submission"
      submission = commentable
      title = "New Comment on #{submission.challenge.title} from #{user.display_name}"
      path = Rails.application.routes.url_helpers.challenge_submission_path(submission.challenge_id, submission)

      # notify each user that's commented, and the owner of this submission, but not the commenter
      users = (submission.comments.map(&:user) + [submission.user]).uniq - [user]

      users.each{|u|
        NotificationsChannel.broadcast_to(u, {
          title: title,
          body: body,
          path: path,
        })
      }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :ensure_admin!, except: [:index, :show, :new, :create, :update]

  # GET /comments
  def index
    @comments = Comment.order(created_at: :asc)

    commentable_id   = params["commentable_id"].try(:to_i)
    commentable_type = params["commentable_type"]
    if commentable_id && commentable_type
      @comments = @comments.where(commentable_id: commentable_id, commentable_type: commentable_type)
    end

    @comments = @comments.group_by(&:parent_id)

    if params[:hideLayout]
      render partial: 'comments/list', locals: {
        comments: @comments,
        commentable_id: commentable_id,
        commentable_type: commentable_type,
      }, layout: 'layouts/hide_layout'
    else
      # @submission = Submission.find(commentable_id) if commentable_type.downcase == "submission"
      render 'comments/index'
    end
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    if @comment.save
      if request.xhr?
        # render :json => {success: true}
        render partial: 'comments/list_item', locals: {comment: @comment}
      else
        redirect_to @comment.commentable, notice: 'Comment saved'
      end
    else
      if request.xhr?
        render partial: 'comments/form', locals: {comment: @comment}
      else
        redirect_to @comment.commentable, notice: 'Error saving comment'
      end
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :commentable_id, :commentable_type, :parent_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="media ajaxReplace">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://www.gravatar.com/avatar/bfed2f6a921d93feb957ebf05f8ca7fb?s=128" alt="..." style="width: 64px; height: 64px;" />
    </a>
  </div>
  <div class="media-body">
    <%= bootstrap_form_for(comment, remote: true) do |f| %>
      <%= f.alert_message "Please fix the errors below." %>

      <%= f.text_area :body, markdown: true, hide_markdown_toobar: true, hide_label: true %>

      <%= f.hidden_field :commentable_id %>
      <%= f.hidden_field :commentable_type %>
      <%= f.hidden_field :parent_id %>

      <div class="pull-right">
        <%= f.submit "Comment", class: "btn btn-success" %>
      </div>
      <div class="clearfix"></div>
    <% end %>
  </div>
</div>

app/views/comments/_list.html.erb
<% parent_id ||= nil %>
<% commentable_id ||= nil %>
<% commentable_type ||= nil %>

<% comments = comments.group_by(&:parent_id) unless comments.class == Hash %>

<div class="comments">
  <% comments[parent_id].each do |comment| %>
    <%= render 'comments/list_item', comment: comment, comments: comments %>
  <% end if comments[parent_id] %>

  <% if parent_id == nil %>
    <%= render 'comments/form', comment: Comment.new(commentable_id: commentable_id, commentable_type: commentable_type, parent_id: parent_id) %>
  <% end %>
</div>

app/views/comments/_list_item.html.erb
<% comments ||= [] %>

<ul class="media-list">
  <li class="media">
    <div class="media-left">
      <%= gravitar_image_tag comment.cached_user_email, size: "64x64", class: 'media-object' %>
    </div>
    <div class="media-body">
      <h5 class="media-heading">
        <%= comment.cached_user_name %> <small>• <%= time_ago_in_words comment.updated_at %> ago</small>
      </h5>
      <%= markdown(comment.body).html_safe %>
      <div style="margin-top: -10px; margin-bottom: 10px; display: none">
        <a href="#">Like</a> <small>•</small>
        <a href="#">Reply</a> <small>•</small>

        <span class="text-primary">
          <%= fa_icon('thumbs-up', text: 1) %>
        </span>
      </div>

      <%= render 'comments/list', comments: comments, parent_id: comment.id %>

    </div>
  </li>
</ul>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<%= render 'comments/list', comments: @comments %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= debug @comment %>