config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: {
    # confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'user/passwords',
    registrations: 'user/registrations',
    sessions: 'user/sessions',
    # unlocks: 'users/unlocks',
  }
  # devise_for :users

  resources :challenges do
    resources :submissions do
      member do
        post :like
      end
    end
  end

  resources :users

  get '/submissions', to: "submissions#index"
  root to: "challenges#index"
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :challenge, counter_cache: true
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  acts_as_votable
  serialize :cached_user_ids_liked, Array
  before_create :refresh_cached_username
  after_commit :update_user_cached_submission_points
  # after_save :update_user_cached_submission_points
  # before_save :update_user_cached_submission_points
  after_update :send_notification

  def public?
    !is_private
  end

  def viewable_by?(user)
    public? || user.try(:admin?) || user_id == user.try(:id)
  end

  def refresh_cached_username
    self.cached_username = user.try(:display_name)
  end

  def update_cached_username
    refresh_cached_username
    save
  end

  # def unliked_by(user)
  #   puts "unliking"
  #   # super(user)
  # end

  # def liked_by(user)
  #   puts "liking"
  #   # super(user)
  # end

  def update_cached_votes(vote_scope)
    self.cached_user_ids_liked = votes_for.pluck(:voter_id)
    save
    super(vote_scope)
  end

  def voted_on_by? voter
    # super(voter)
    cached_user_ids_liked.include?(voter.id)
  end

  def update_user_cached_submission_points
    # TODO: this breaks on the first submission
    if false || id_changed? || points_changed? || points_previously_changed?
      highest = Submission.where(challenge_id: challenge_id, user_id: user_id).order(points: :desc).limit(1).pluck(:points).first
      user.update(cached_submission_points: user.cached_submission_points.merge({challenge_id => highest}))
    end
  end

  private

  def send_notification
    NotificationsChannel.broadcast_to(user, {
      title: "#{challenge.title} Graded",
      body: "You got #{points}/#{challenge.points} points.",
      path: Rails.application.routes.url_helpers.challenge_submission_path(challenge, self),
      type: points && points > 0 ? (points > challenge.points ? "success" : "info") : "warning"
    })
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :like, :destroy]
  before_action :set_challenge, only: [:show, :edit, :update, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :ensure_admin!, except: [:show, :new, :create, :update, :like]

  # GET /submissions
  def index
    @submissions = Submission.includes(:challenge).where(points: nil).group_by(&:challenge_id)
  end

  # GET /submissions/1
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  def create
    @submission = Submission.new(submission_params.merge(
      user: current_user,
      challenge: @challenge,
    ))

    if @submission.save
      redirect_to challenge_path(@challenge, anchor: 'submissions'), notice: 'Your submission was sent and is queued to be checked'
    else
      render :new
    end
  end

  # PATCH/PUT /submissions/1
  def update
    if @submission.update(submission_params)
      if request.xhr?
        # render :json => {success: true}

        render 'submissions/_list_item', locals: {submission: @submission}, layout: false
      else
        redirect_to @submission, notice: 'Submission was successfully updated.'
      end
    else
      if request.xhr?
        # render :json => @submission.errors, :status => :unprocessable_entity
        render 'submissions/_list_item', locals: {submission: @submission}, layout: false
      else
        render :edit
      end
    end
  end

  def like
    if current_user.voted_up_on?(@submission)
      @submission.unliked_by(current_user)
    else
      current_user.likes(@submission)
    end
    render 'submissions/_list_item', locals: {submission: @submission}, layout: false
  end

  # DELETE /submissions/1
  def destroy
    @submission.destroy
    redirect_to submissions_url, notice: 'Submission was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    def set_challenge
      @challenge  = Challenge.find(params[:challenge_id])
    end

    # Only allow a trusted parameter "white list" through.
    def submission_params
      if current_user.try(:admin?)
        params.require(:submission).permit(:challenge_id, :user_id, :is_private, :approved_at, :denied_at, :url, :content, :points)
      else
        params.require(:submission).permit(:is_private, :url, :content)
      end
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  def list_group_class_for_score(score)
    if score.blank?
      "list-group-item-warning"
    elsif score <= 0
      "list-group-item-danger"
    elsif score <= 1
      "list-group-item-info"
    else
      "list-group-item-success"
    end
  end
end

app/views/submissions/_form.html.erb
<!-- layout: :inline -->
<%= bootstrap_form_for([challenge, submission]) do |f| %>
  <%= f.alert_message "Please fix the errors below." %>
  <%=
    f.url_field :url,
      hide_label: true,
      placeholder: "Solution URL",
      prepend: f.check_box(:is_private, label: fa_icon('user-secret', text: "private")),
      append: f.submit("Send", class: 'btn btn-info')
  %>
  <%# f.text_area :content %>
<% end %>

app/views/submissions/_list.html.erb
<div class="list-group">
  <% submissions.each do |submission| %>
    <%= render 'submissions/list_item', submission: submission %>
  <% end %>
</div>

<% if submissions.empty? %>
No solutions yet.
<% end %>


<!-- <ul class="list-group">
  <li class="list-group-item">Dapibus ac facilisis in</li>
  <li class="list-group-item disabled">Dapibus ac facilisis in</li>
  <li class="list-group-item list-group-item-success">Dapibus ac facilisis in</li>
  <li class="list-group-item list-group-item-info">Cras sit amet nibh libero</li>
  <li class="list-group-item list-group-item-warning">Porta ac consectetur ac</li>
  <li class="list-group-item list-group-item-danger">Vestibulum at eros</li>
</ul>

 -->

app/views/submissions/_list_item.html.erb
<% item_class = submission.viewable_by?(current_user) ? "" : "disabled" %>
<%
  item_class += submission.user_id == current_user.try(:id) ? list_group_class_for_score(submission.points && 1.0 * submission.points / submission.challenge.points) : ""
%>
<% submission_url = submission.viewable_by?(current_user) ? submission.url : "#nice_try" %>
<% submission_tag = submission.viewable_by?(current_user) ? 'a' : "span" %>

<<%= submission_tag %> href="<%= submission_url %>" class="list-group-item <%= item_class %>" target="_blank">
  <%# link_to submission.url, submission.url, target: "_blank" %>
  <p class="list-group-item-text">
    <div class="pull-right">
      <% if current_user %>
      <!-- @user.voted_up_on? @comment1 -->
        <% like_button_class = submission.voted_on_by?(current_user) ? 'btn-primary' : 'btn-default' %>
        <%= html_button_to fa_icon('thumbs-up', text: 'Like'), like_challenge_submission_path(submission.challenge, submission),
          class: "btn btn-sm #{like_button_class}",
          remote: true
        %>

        <%= html_button_to fa_icon('comment', text: submission.comments_count),
          comments_path(commentable_id: submission.id, commentable_type: 'Submission', hideLayout: true),
          data: {modal: true, title: "Comments"},
          class: 'btn btn-default btn-sm'
        %>
      <% end %>

      <% if admin? || submission.user_id == current_user.try(:id) %>
        <% secret_button_class = submission.is_private ? "btn-primary" : "btn-default" %>
        <%= html_button_to fa_icon('user-secret', text: ""), challenge_submission_path(submission.challenge, submission),
          class: "btn btn-sm #{secret_button_class}",
          remote: true,
          method: :patch,
          params: {
            submission: {
              is_private: !submission.is_private
            }
          }
        %>
      <% end %>

      <% if admin? %>
        <%= html_button_to fa_icon('times'), challenge_submission_path(submission.challenge, submission),
          class: 'btn btn-default btn-sm',
          remote: true,
          method: :patch,
          params: {
            submission: {
              points: 0
            }
          }
        %>

        <%= html_button_to fa_icon('check'), challenge_submission_path(submission.challenge, submission),
          class: 'btn btn-default btn-sm',
          remote: true,
          method: :patch,
          params: {
            submission: {
              points: submission.challenge.points
            }
          }
        %>

        <%= html_button_to fa_icon('check', text: "+"), challenge_submission_path(submission.challenge, submission),
          class: 'btn btn-default btn-sm',
          remote: true,
          method: :patch,
          params: {
            submission: {
              points: (submission.challenge.points * 1.3).round
            }
          }
        %>
      <% end %>
    </div>

    <% if submission.points %>
      <% label_class = submission.points > 0 ? (submission.points > submission.challenge.points ? 'label-success' : 'label-info') : 'label-default'%>
      <span class="label <%= label_class %>"><%= fa_icon 'star', text: submission.points %></span>
    <% end %>
    <span class="label label-primary"><%= fa_icon 'thumbs-up', text: submission.cached_votes_up %></span>
    <%= submission.cached_username %>
    <small>solved <%= time_ago_in_words submission.created_at %> ago</small>

  </p>
  <!-- <h4 class="list-group-item-heading">List group item heading</h4> -->
  <!-- <p class="list-group-item-text"> -->
  <!-- </p> -->
  <div class="clearfix"></div>
</<%= submission_tag %>>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission, challenge: @challenge %>

<%# link_to 'Show', @submission %> |
<%# link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<% @submissions.each do |challenge_id, submissions| %>
  <% challenge = Challenge.find(challenge_id) %>
    <h2><%= link_to challenge.name, challenge_path(challenge_id) %></h2>

    <% unless challenge.challenge.blank? %>
      <%= markdown(challenge.challenge).html_safe %>
    <% end %>

    <%= render 'submissions/list', submissions: submissions %>
  <% end %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission, challenge: @challenge %>

<%# link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<h1><%= link_to "#{@challenge.title}", @challenge %></h1>

hello world

<% unless @challenge.challenge.blank? %>
  <%= markdown(@challenge.challenge).html_safe %>
<% end %>

<%= render 'submissions/list_item', submission: @submission %>
<br/>

<%= render 'comments/list', comments: @submission.comments, commentable_id: @submission.id, commentable_type: @submission.class %>