config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: {
    # confirmations: 'users/confirmations',
    # omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'user/passwords',
    registrations: 'user/registrations',
    sessions: 'user/sessions',
    # unlocks: 'users/unlocks',
  }
  # devise_for :users

  resources :challenges do
    resources :submissions do
      member do
        post :like
      end
    end
  end

  resources :users

  get '/submissions', to: "submissions#index"
  root to: "challenges#index"
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  # acts_as_taggable_on :tags
  has_many :submissions, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  def title
    self.name =~ /[\d\.]+\s*(.*)/
    $1 || self.name
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:edit, :update, :destroy]
  before_action :set_challenge_with_submissions, only: [:show]

  before_action :authenticate_user!, except: [:index, :show]
  before_action :ensure_admin!, except: [:index, :show, :new, :create]
  # before_action :authenticate_user!

  # GET /challenges
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  def show
    # # @challenge.includes(:submissions)
    # @submissions = @challenge.submissions
    @comments = Comment.where(commentable_id: @challenge.id).group_by(&:parent_id)
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  def create
    @challenge = Challenge.new(challenge_params)

    if @challenge.save
      redirect_to @challenge, notice: 'Challenge was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /challenges/1
  def update
    if @challenge.update(challenge_params)
      redirect_to @challenge, notice: 'Challenge was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /challenges/1
  def destroy
    @challenge.destroy
    redirect_to challenges_url, notice: 'Challenge was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    def set_challenge_with_submissions
      @challenge = Challenge.includes(:submissions).find(params[:id])
      # @submissions = @challenge.submissions.order(cached_votes_total: :desc)
      @submissions = @challenge.submissions.order(points: :desc)
      # .sort_by(&:cached_votes_total)
      # order(cached_votes_total: :desc)
    end

    # Only allow a trusted parameter "white list" through.
    def challenge_params
      params.require(:challenge).permit(:description, :name, :is_locked, :category, :tag_list, :points, :challenge)
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_breadcrumbs.html.erb
<ol class="breadcrumb">
  <li>
    <%= link_to 'Challenges', challenges_path %>
  </li>
  <% if challenge %>
    <li>
      <%= link_to challenge.category, challenges_path(anchor: challenge.category) %>
    </li>
    <li>
      <%= link_to challenge.name, challenge %>
    </li>
  <% end %>
  <!-- <li class="active">Data</li> -->
</ol>

app/views/challenges/_form.html.erb
<% categories = ["00 HTML", "01 CSS", "02 Javascript", "03 Mobile", "04 Hacking", "05 Games", "06 Toys", "07 Puzzles", "08 Tools", "08 Webmastering", "09 Business"] %>

  <%= bootstrap_form_for(challenge) do |f| %>
  <%= f.text_field :name %>
  <%= f.select :category, categories, { label: "Categry:" } %>
  <%= f.check_box :is_locked %>
  <%= f.number_field :points %>
  <%= f.text_area :description, markdown: true %>
  <%= f.text_area :challenge, markdown: true %>
  <%= f.submit "Save", class: "btn btn-lg btn-primary" %>
  <%= link_to 'Cancel', challenge.new_record? ? challenges_path : challenge, class: "btn btn-lg btn-default" %>
<% end %>

app/views/challenges/edit.html.erb
<%# render 'breadcrumbs', challenge: @challenge %>

<%= render 'form', challenge: @challenge %>

app/views/challenges/index.html.erb
<!-- <h1>Challenges</h1> -->

<% @challenges.group_by(&:category).sort_by{|c,_| c.try(:to_f)}.each do |category, challenges| %>
  <h2><a name="<%= category %>"></a><%= strip_order category %></h2>
  <div class="list-group">
    <% challenges.sort_by{|c| c.try(:name).try(:to_f)}.each do |challenge| %>
      <% points = current_user ? current_user.cached_submission_points[challenge.id] : nil %>
      <% list_item_class = points ? list_group_class_for_score(1.0 * points / challenge.points) : '' %>
      <% list_item_class += " disabled" if challenge.is_locked %>
      <% challenge_tag = (challenge.is_locked && !admin?) ? 'div' : 'a' %>

      <<%= challenge_tag %> href="<%= challenge_url(challenge) %>" class="list-group-item <%= list_item_class %>">
        <!-- <span class="badge">14</span> -->
        <%= fa_icon(:lock) if challenge.is_locked %>
        <%= strip_order challenge.name %>

        <span class="pull-right">
          <% if admin? %>
            <span class="label label-default"><%= fa_icon 'trophy', text: challenge.submissions_count %></span>
          <% end %>

          <% label_class = (points && points > 0) ? (points > challenge.points ? 'label-success' : 'label-info') : 'label-default'%>
          <% points_text = challenge.points.to_s %>
          <% points_text = ("#{points}/#{challenge.points}") if points %>
          <span class="label <%= label_class %>"><%= fa_icon 'star', text: points_text %></span>
        </span>

      </<%= challenge_tag %>>
    <% end %>
  </div>
<% end %>

<br>

<%= link_to 'New Challenge', new_challenge_path, class: 'btn btn-success' %>

app/views/challenges/new.html.erb
<%# render 'breadcrumbs', challenge: @challenge %>

<%= render 'form', challenge: @challenge %>

app/views/challenges/show.html.erb
<%# render 'breadcrumbs', challenge: @challenge %>

  <h1>
    <% if admin? %>
      <div class="pull-right">
        <%= link_to 'Edit', edit_challenge_path(@challenge), class: "btn btn-default" %>
        <%= link_to 'Destroy', @challenge, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    <% end %>

    <%= @challenge.title %>
  </h1>

  <div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist" style="display: none">
      <li role="presentation" class="active">
        <a href="#instructions" aria-controls="instructions" role="tab" data-toggle="tab">
          <%= fa_icon('book') %>
          Instructions
        </a>
      </li>
      <li role="presentation">
        <a href="#questions" aria-controls="questions" role="tab" data-toggle="tab">
          <%= fa_icon('comments') %>
          Questions
        </a>
      </li>
      <li role="presentation">
        <a href="#solutions" aria-controls="solutions" role="tab" data-toggle="tab">
          <%= fa_icon('trophy') %>
          Solutions
          <span class="badge"><%= @challenge.submissions_count %></span>
        </a>
      </li>
    </ul>

    <br>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="instructions">
        <div class="row">
          <div class="challenge-description col-md-8">
            <%= markdown(@challenge.description).html_safe %>

            <% unless @challenge.challenge.blank? %>
              <hr/>
              <h2>Challenge</h2>
              <%= markdown(@challenge.challenge).html_safe %>
            <% end %>

            <%= render 'submissions/form', challenge: @challenge, submission: Submission.new %>

            <hr/>

            <h2>Solutions</h2>

            <% if current_user && (admin? || current_user.cached_submission_points.has_key?(@challenge.id)) %>
              <%= render 'submissions/list', submissions: @submissions %>
            <% else %>
              <p>Try this challenge on your own first, then come back here to see other people's solutions.</p>
            <% end %>
          </div>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane" id="questions">
        <div class="row">
          <div class="col-md-8">
            <%= render 'comments/list', comments: @comments, commentable_id: @challenge.id, commentable_type: @challenge.class %>
          </div>
        </div>
      </div>
      <div role="tabpanel" class="tab-pane" id="solutions">
        <div class="row">
          <div class="col-md-8">
            <% if current_user && (admin? || current_user.cached_submission_points.has_key?(@challenge.id)) %>
              <%= render 'submissions/list', submissions: @submissions %>
            <% else %>
              <p>Try this challenge on your own first, then come back here to see other people's solutions.</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>

  <%# render 'submissions/list', submissions: @submissions %>